# emcpy/pytest.ini
[pytest]
minversion = 7.0

# Your tests live under src/tests
testpaths =
    src/tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Default flags (can override on CLI)
addopts = -q -ra --maxfail=1

markers =
    image: image-regression / slower
    maps: tests requiring cartopy
    slow: slow tests

filterwarnings =
    error::FutureWarning
    error::DeprecationWarning

norecursedirs =
    .git
    .venv
    build
    dist
    .mplconfig
