name: Build & Deploy Docs

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true }
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip/wheel/setuptools
        run: python -m pip install -U pip wheel setuptools

#      - name: Install docs deps
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r docs/requirements.txt

      - name: Install package with docs extras
        run: pip install .[docs]

      - name: Build docs (fail on warnings)
        run: sphinx-build -b html -W -q docs _build/html

      - name: Deploy to gh-pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _build/html
