name: Run tests
on: [push, pull_request]

jobs:
  run_pytests:
    runs-on: ubuntu-latest
    name: Install and run tests with pytests

    steps:

    - name: Install (upgrade) dependencies
      run: |
        pip install --upgrade pip
        pip install pytest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: emcpy

    - name: Install emcpy
      run: |
        cd $GITHUB_WORKSPACE/emcpy
        pip install .

    - name: Run pytests
      run: |
        cd $GITHUB_WORKSPACE/emcpy
        pytest -v src/tests
