name: Run tests
on: [push, pull_request]

jobs:
  run_pytests:
    runs-on: ubuntu-latest
    name: Install and run tests with pytests

    steps:

    # Setup Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    # Update conda
    - name: Update conda
      run: conda update -n base -c defaults conda

    # Intall pip
    - name: Install pip
      run: conda install pip
    
    # Install cartopy
    - name: Install cartopy
      run: conda install -c conda-forge cartopy

    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    # Install emcpy
    - name: Upgrade pip
      run: $CONDA/bin/pip3 install --upgrade pip
    - name: Install emcpy and dependencies
      run: |
        $CONDA/bin/pip3 install --use-deprecated=legacy-resolver -r requirements-github.txt --user .
        echo "$PWD" 

    # Run empcy test suite
    - name: Run emcpy pytests
      run: |
        cd $GITHUB_WORKSPACE
        pytest -v src/tests

    # Generate documentation
    - name: Generate documentation
      run: |
        cd $GITHUB_WORKSPACE
        pdoc --docformat "google" -o docs emcpy
        ls -lR docs/

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
