name: Run tests
on: [push, pull_request]

jobs:
  run_pytests:
    runs-on: ubuntu-latest
    name: Install and run tests with pytests

    steps:

    - name: Install ubuntu dependencies
      run: |
        sudo apt-get install libproj-dev proj-data proj-bin
        sudo apt-get install libgeos-dev musl-dev libc-dev
        sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

    - name: Install (upgrade) dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
        pip install pdoc
        pip install Shapely

    # Update conda
    - name: Update conda
      run: conda update -n base -c defaults conda

    # Install cartopy
    - name: Install cartopy
      run: conda install -c conda-forge cartopy

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: emcpy

    - name: Upgrade pip
      run: $CONDA/bin/pip3 install --upgrade pip
    - name: Install emcpy and dependencies
      run: $CONDA/bin/pip3 install --use-deprecated=legacy-resolver -r requirements-github.txt --user .
    - name: Put emcpy in the path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

#    - name: Install emcpy
      #run: |
      #  cd $GITHUB_WORKSPACE/emcpy
      #  pip install .
      #  $CONDA/bin/pip3 install --use-deprecated=legacy-resolver -r requirements-github.txt --user .

    - name: Run pytests
      run: |
        cd $GITHUB_WORKSPACE/emcpy
        pytest -v src/tests

    - name: Generate documentation
      run: |
        cd $GITHUB_WORKSPACE
        pdoc --docformat "google" -o docs emcpy
        ls -lR docs/

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
